name: Docker Image CI for GHCR

on:
    push
jobs:
    build_and_publish:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Build and push the image
              run: |
                docker login --username practicum16greeava --password ${{secrets.ACCESS_TOKEN}} ghcr.io
                docker build -t ghcr.io/greeava04/arithmetic-service:latest --file Dockerfile .  
                docker push ghcr.io/greeava04/arithmetic-service:latest 
            - name: Publish the image to azure container registry
              run: |
                docker login --usernamepracticum16greeava --password ${{secrets.AZURE_CONTAINER_REGISTRY}} practicum16greeava.azurecr.io
                docker tag ghcr.io/greeava04/arithmetic-service:1 practicum16greeava.azurecr.io/arithmetic-service:1
                docker push practicum16greeava.azurecr.io/arithmetic-service:1